export const PLAN_DEFINITIONS = [
  {
    planId: "free",
    name: "Free",
    monthlyPrice: 0,
    allowedBillingCycles: ["free"],
    listingLimit: 5,
    commissionRate: 2,
    payoutMinimumDays: 7,
    payoutMaximumDays: 10,
    analyticsLevel: "basic",
    staffAccountMinimum: 0,
    staffAccountMaximum: 0,
    features: [
      "5 active artworks",
      "Basic artist profile",
      "Basic analytics",
      "Orders, messages and promotions",
    ],
    permissions: [
      "overview",
      "store",
      "artworks",
      "orders",
      "messages",
      "promotions",
      "shipping",
      "payouts",
      "reviews",
      "verification",
      "subscription",
      "support",
      "settings",
      "analytics",
    ],
    recommended: false,
    isActive: true,
    sortOrder: 0,
  },
  {
    planId: "professional",
    name: "Professional",
    monthlyPrice: 1999,
    annualPrice: 22990,
    allowedBillingCycles: ["monthly", "annual"],
    listingLimit: 50,
    commissionRate: 1.5,
    payoutMinimumDays: 5,
    payoutMaximumDays: 7,
    analyticsLevel: "detailed",
    staffAccountMinimum: 0,
    staffAccountMaximum: 0,
    features: [
      "50 active artworks",
      "Detailed analytics",
      "Portfolio link",
      "Priority support",
      "Verification review",
    ],
    permissions: [
      "overview",
      "store",
      "artworks",
      "orders",
      "messages",
      "promotions",
      "shipping",
      "payouts",
      "reviews",
      "verification",
      "subscription",
      "support",
      "settings",
      "analytics",
      "portfolio",
      "priority-support",
    ],
    recommended: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    planId: "pro-plus",
    name: "Pro Plus",
    monthlyPrice: 3999,
    annualPrice: 34999,
    allowedBillingCycles: ["monthly", "annual"],
    listingLimit: 200,
    commissionRate: 1,
    payoutMinimumDays: 3,
    payoutMaximumDays: 5,
    analyticsLevel: "advanced",
    staffAccountMinimum: 0,
    staffAccountMaximum: 0,
    features: [
      "200 active artworks",
      "Advanced analytics",
      "International selling tools",
      "Store URL",
      "Customer-management tools",
      "Verification review",
    ],
    permissions: [
      "overview",
      "store",
      "artworks",
      "orders",
      "messages",
      "promotions",
      "shipping",
      "payouts",
      "reviews",
      "verification",
      "subscription",
      "support",
      "settings",
      "analytics",
      "advanced-analytics",
      "customers",
      "premium-url",
      "international-tools",
    ],
    recommended: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    planId: "gallery",
    name: "Gallery",
    monthlyPrice: 10000,
    allowedBillingCycles: ["monthly"],
    listingLimit: null,
    commissionRate: 0,
    payoutMinimumDays: 3,
    payoutMaximumDays: 5,
    analyticsLevel: "advanced",
    staffAccountMinimum: 3,
    staffAccountMaximum: 10,
    features: [
      "Fair-use unlimited listings",
      "3–10 staff accounts",
      "Gallery storefront",
      "CRM",
      "Artist management",
      "Inventory management",
      "Exhibitions",
      "Reports",
    ],
    permissions: [
      "overview",
      "store",
      "artworks",
      "orders",
      "messages",
      "promotions",
      "shipping",
      "payouts",
      "reviews",
      "verification",
      "subscription",
      "support",
      "settings",
      "analytics",
      "advanced-analytics",
      "customers",
      "premium-url",
      "international-tools",
      "managed-artists",
      "staff",
      "staff-permissions",
      "inventory",
      "exhibitions",
      "gallery-crm",
      "reports",
    ],
    recommended: false,
    isActive: true,
    sortOrder: 3,
  },
] as const;

export const PLAN_RANK: Record<string, number> = {
  free: 0,
  professional: 1,
  "pro-plus": 2,
  gallery: 3,
};

export const PROMOTION_PRICES: Record<
  string,
  { minimum: number; maximum: number; durationDays: number; approval: boolean }
> = {
  boost_3: { minimum: 299, maximum: 299, durationDays: 3, approval: false },
  boost_7: { minimum: 699, maximum: 699, durationDays: 7, approval: false },
  category_top: { minimum: 1499, maximum: 1499, durationDays: 7, approval: false },
  featured_artist: { minimum: 2499, maximum: 2499, durationDays: 7, approval: true },
  homepage: { minimum: 4999, maximum: 4999, durationDays: 7, approval: true },
  social: { minimum: 5000, maximum: 15000, durationDays: 7, approval: true },
  newsletter: { minimum: 2000, maximum: 5000, durationDays: 7, approval: true },
};
