/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellRouteImport } from './routes/sell'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuyerProtectionRouteImport } from './routes/buyer-protection'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CreatorSlugRouteImport } from './routes/creator.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProtectionRoute = BuyerProtectionRouteImport.update({
  id: '/buyer-protection',
  path: '/buyer-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/creator/$slug',
  path: '/creator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/creators': typeof CreatorsRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/creators': typeof CreatorsRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/creators': typeof CreatorsRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buyer-protection'
    | '/cart'
    | '/collections'
    | '/creators'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/sell'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buyer-protection'
    | '/cart'
    | '/collections'
    | '/creators'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/sell'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buyer-protection'
    | '/cart'
    | '/collections'
    | '/creators'
    | '/discover'
    | '/how-it-works'
    | '/journal'
    | '/sell'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/creator/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyerProtectionRoute: typeof BuyerProtectionRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRoute
  CreatorsRoute: typeof CreatorsRoute
  DiscoverRoute: typeof DiscoverRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JournalRoute: typeof JournalRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CreatorSlugRoute: typeof CreatorSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-protection': {
      id: '/buyer-protection'
      path: '/buyer-protection'
      fullPath: '/buyer-protection'
      preLoaderRoute: typeof BuyerProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$slug': {
      id: '/creator/$slug'
      path: '/creator/$slug'
      fullPath: '/creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyerProtectionRoute: BuyerProtectionRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRoute,
  CreatorsRoute: CreatorsRoute,
  DiscoverRoute: DiscoverRoute,
  HowItWorksRoute: HowItWorksRoute,
  JournalRoute: JournalRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CreatorSlugRoute: CreatorSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
